.PHONY: clean All

All:
	@echo "----------Building project:[ Section_11_Final_KILLER - Debug ]----------"
	@cd "Section_11_Final_KILLER" && "$(MAKE)" -f  "Section_11_Final_KILLER.mk"
clean:
	@echo "----------Cleaning project:[ Section_11_Final_KILLER - Debug ]----------"
	@cd "Section_11_Final_KILLER" && "$(MAKE)" -f  "Section_11_Final_KILLER.mk" clean
